# docker-compose.yml
version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7687:7687"
      - "7474:7474"
